#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
# UBUNTU SERVER SETUP — Sistem Tempahan Bilik Media
# Tested on: Ubuntu 22.04 / 24.04 LTS
# Run sebagai user dengan sudo (BUKAN root):
#   chmod +x deploy/ubuntu-setup.sh
#   ./deploy/ubuntu-setup.sh
# ═══════════════════════════════════════════════════════════

set -e   # Berhenti kalau ada error
set -u   # Berhenti kalau ada variable tak set

# ── Konfigurasi default ─────────────────────────────────────
DOMAIN="${DOMAIN:-tempahan.byzaifuan.com}"
DB_NAME="${DB_NAME:-tempahan_db}"
DB_USER="${DB_USER:-tempahan_user}"
DB_PASS="${DB_PASS:-$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)}"
APP_PORT="${APP_PORT:-3000}"
NODE_VERSION="${NODE_VERSION:-20}"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log() { echo -e "${GREEN}[setup]${NC} $1"; }
warn() { echo -e "${YELLOW}[warn]${NC} $1"; }
err() { echo -e "${RED}[err]${NC} $1"; exit 1; }

if [[ $EUID -eq 0 ]]; then
   err "JANGAN run sebagai root. Run sebagai user biasa dengan sudo access."
fi

# ── 1. Update sistem ───────────────────────────────────────
log "Update sistem..."
sudo apt update && sudo apt upgrade -y

# ── 2. Install dependencies asas ───────────────────────────
log "Install dependencies asas..."
sudo apt install -y curl wget git build-essential ca-certificates gnupg lsb-release \
                    ufw fail2ban software-properties-common openssl

# ── 3. Install Node.js ─────────────────────────────────────
if ! command -v node >/dev/null 2>&1 || [[ "$(node -v | cut -d. -f1 | tr -d 'v')" -lt "${NODE_VERSION}" ]]; then
  log "Install Node.js ${NODE_VERSION}..."
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_VERSION}.x" | sudo -E bash -
  sudo apt install -y nodejs
fi
log "Node.js: $(node -v) | npm: $(npm -v)"

# ── 4. Install PostgreSQL ──────────────────────────────────
if ! command -v psql >/dev/null 2>&1; then
  log "Install PostgreSQL..."
  sudo apt install -y postgresql postgresql-contrib
fi
log "PostgreSQL: $(psql --version)"
sudo systemctl enable --now postgresql

# ── 5. Setup database + user ───────────────────────────────
log "Setup database '${DB_NAME}' & user '${DB_USER}'..."
sudo -u postgres psql <<EOF
DO \$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
      CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';
   ELSE
      ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASS}';
   END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
ALTER DATABASE ${DB_NAME} SET timezone TO 'Asia/Kuala_Lumpur';
EOF

# Grant schema access (PG 15+)
sudo -u postgres psql -d "${DB_NAME}" -c "GRANT ALL ON SCHEMA public TO ${DB_USER};"

# ── 6. Install Nginx ───────────────────────────────────────
if ! command -v nginx >/dev/null 2>&1; then
  log "Install Nginx..."
  sudo apt install -y nginx
fi
sudo systemctl enable --now nginx

# ── 7. Install PM2 (process manager) ───────────────────────
if ! command -v pm2 >/dev/null 2>&1; then
  log "Install PM2..."
  sudo npm install -g pm2
fi
log "PM2: $(pm2 -v)"

# ── 8. Install certbot (untuk SSL) ─────────────────────────
if ! command -v certbot >/dev/null 2>&1; then
  log "Install Certbot..."
  sudo apt install -y certbot python3-certbot-nginx
fi

# ── 9. Firewall ────────────────────────────────────────────
log "Konfigur UFW firewall..."
sudo ufw allow OpenSSH || true
sudo ufw allow 'Nginx Full' || true
sudo ufw --force enable

# ── 10. Setup .env ─────────────────────────────────────────
ENV_FILE="$(pwd)/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  log "Cipta .env..."
  SESSION_SECRET=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)
  JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)
  cat > "$ENV_FILE" <<EOF
# Auto-generated by ubuntu-setup.sh
NODE_ENV=production
PORT=${APP_PORT}
TZ=Asia/Kuala_Lumpur

# Database
DB_HOST=localhost
DB_PORT=5432
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASS}

# Secrets
SESSION_SECRET=${SESSION_SECRET}
JWT_SECRET=${JWT_SECRET}
EOF
  chmod 600 "$ENV_FILE"
  warn "DB password disimpan dalam .env (chmod 600)."
else
  warn ".env sedia ada — skip."
fi

# ── 11. Install npm dependencies ───────────────────────────
if [[ -f package.json ]]; then
  log "Install npm dependencies..."
  npm install --omit=dev
fi

# ── 12. Cipta direktori logs ───────────────────────────────
mkdir -p logs

# ── 13. Init database schema ───────────────────────────────
log "Init database schema..."
npm run init-db || warn "init-db gagal — mungkin schema sedia ada"

# ── 14. Setup nginx config ─────────────────────────────────
NGINX_CONF="/etc/nginx/sites-available/sistem-tempahan"
if [[ ! -f "$NGINX_CONF" ]]; then
  log "Setup Nginx config (HTTP sahaja dahulu — SSL kemudian)..."
  sudo cp nginx/sistem-tempahan.conf "$NGINX_CONF"
  sudo sed -i "s/tempahan.byzaifuan.com/${DOMAIN}/g" "$NGINX_CONF"

  # Sementara — disable HTTPS block sehingga SSL dipasang
  warn "Nginx config dipasang. Anda perlu edit ${NGINX_CONF} dan disable block HTTPS sementara, atau terus run certbot."

  sudo ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/sistem-tempahan
  sudo rm -f /etc/nginx/sites-enabled/default
  sudo nginx -t && sudo systemctl reload nginx
else
  warn "Nginx config sedia ada — skip."
fi

# ── DONE ──────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════"
echo -e "${GREEN}✅ Setup selesai!${NC}"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Database:"
echo "  Name     : ${DB_NAME}"
echo "  User     : ${DB_USER}"
echo "  Password : (lihat .env)"
echo ""
echo "Langkah seterusnya:"
echo ""
echo "  1) Import data Excel:"
echo "     npm run import-excel -- /path/to/data.xlsx"
echo ""
echo "  2) Cipta admin user (atau guna default admin/admin123):"
echo "     npm run create-admin"
echo ""
echo "  3) Start aplikasi dengan PM2:"
echo "     pm2 start ecosystem.config.js"
echo "     pm2 save"
echo "     pm2 startup    # ikut arahan yang dipaparkan"
echo ""
echo "  4) Setup SSL (selepas DNS A record point ke server ini):"
echo "     sudo certbot --nginx -d ${DOMAIN}"
echo ""
echo "  5) Akses aplikasi:"
echo "     https://${DOMAIN}        (aplikasi utama)"
echo "     https://${DOMAIN}/admin  (admin panel)"
echo ""
echo "═══════════════════════════════════════════════════════════"
